apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-app
  template:
    metadata:
      name: grafana-pod
      labels:
        app: grafana-app
    spec:
      restartPolicy: Always
      containers:
      - name: grafana-container
        image: grafana-image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: grafana
        - containerPort: 8086
          name: influxdb
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "/validity.sh"
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-loadbalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: grafana-app
  ports:
    - protocol: TCP
      port: 3000
      name: grafana