#TODO auto create secrets for mysql password

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-app
  template:
    metadata:
      name: mariadb-pod
      labels:
        app: mariadb-app
    spec:
      containers:
      - name: mariadb-container
        image: mariadb-image
        imagePullPolicy: Never
        ports:
          - containerPort: 3306
            name: mariadb
            # valueFrom:
            #   secretKeyRef:
            #     name: mysql-secrets
            #     key: root-password
        volumeMounts:
        - name: mariadb-secret-volume
          mountPath: /etc/kub/secret-volume
      volumes:
      - name: mariadb-secret-volume
        secret:
          secretName: mariadb-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  type: ClusterIP
  clusterIP: 10.96.0.13
  # type: LoadBalancer
  selector:
    app: mariadb-app
  ports:
    - protocol: TCP
      port: 3306
      name: pma
    - protocol: TCP
      port: 3307
      name: wpdb

