# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pv-claim
#   labels:
#     app: wordpress
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-app
  template:
    metadata:
      name: mariadb-pod
      labels:
        app: mariadb-app
    spec:
      containers:
      - name: mariadb-container
        image: mariadb-image
        imagePullPolicy: Never
        ports:
          - containerPort: 3306
            name: mariadb
        # volumeMounts:
        # - name: mysql-persistent-storage
        #   mountPath: /var/lib/mysql
        # volumes:
        # - name: mysql-persistent-storage
        #   persistentVolumeClaim:
        #     claimName: mysql-pv-claim
            # valueFrom:
            #   secretKeyRef:
            #     name: mysql-secrets
            #     key: root-password
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: ClusterIP
  clusterIP: 10.96.0.13
  # type: LoadBalancer
  selector:
    app: mariadb-app
  ports:
    - protocol: TCP
      port: 3306
      name: mariadb