#TODO auto create secrets for mysql password

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-app
  template:
    metadata:
      name: phpmyadmin-pod
      labels:
        app: phpmyadmin-app
    spec:
      containers:
      - name: phpmyadmin-container
        image: phpmyadmin-image
        imagePullPolicy: Never
        ports:
          - containerPort: 80
            name: phpmyadmin
          - containerPort: 3306
            name: phpdatabase
        volumeMounts:
        - name: phpmyadmin-secret-volume
          mountPath: /etc/kub/secret-volume
      volumes:
      - name: phpmyadmin-secret-volume
        secret:
          secretName: phpmyadmin-secret
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-loadbalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin-app
  ports:
    - protocol: TCP
      port: 5000
      name: phpmyadmin
    - protocol: TCP
      port: 3306
      name: phpdatabase