apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-volume
  labels:
    app: mariadb-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-app
  template:
    metadata:
      name: mariadb-pod
      labels:
        app: mariadb-app
    spec:
      containers:
      - name: mariadb-container
        image: mariadb-image
        imagePullPolicy: Never
        ports:
          - containerPort: 3306
            name: mariadb
        volumeMounts:
        - name: mariadb-secret-volume
          mountPath: /etc/kub/secret-volume
        - name: mariadb-persistent-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-secret-volume
        secret:
          secretName: mariadb-secret
      - name: mariadb-persistent-volume
        persistentVolumeClaim:
          claimName: mariadb-volume
        # volumeMounts:
        # - name: mysql-persistent-storage
        #   mountPath: /var/lib/mysql
        # volumes:
        # - name: mysql-persistent-storage
        #   persistentVolumeClaim:
        #     claimName: mysql-pv-claim
            # valueFrom:
            #   secretKeyRef:
            #     name: mysql-secrets
            #     key: root-password
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  type: ClusterIP
  clusterIP: 10.96.0.13
  selector:
    app: mariadb-app
  ports:
    - protocol: TCP
      port: 3306
      name: pma
    - protocol: TCP
      port: 3307
      name: wpdb

