apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume
  labels:
    app: mysql-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql-app
    spec:
      restartPolicy: Always
      containers:
      - name: mysql-container
        image: mysql-image
        imagePullPolicy: Never
        ports:
          - containerPort: 3306
            name: mysql
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "/validity.sh"
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 3
        volumeMounts:
        - name: mysql-secret-volume
          mountPath: /etc/kub/secret-volume
        - name: mysql-persistent-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-secret-volume
        secret:
          secretName: mysql-secret
      - name: mysql-persistent-volume
        persistentVolumeClaim:
          claimName: mysql-volume
        # volumeMounts:
        # - name: mysql-persistent-storage
        #   mountPath: /var/lib/mysql
        # volumes:
        # - name: mysql-persistent-storage
        #   persistentVolumeClaim:
        #     claimName: mysql-pv-claim
            # valueFrom:
            #   secretKeyRef:
            #     name: mysql-secrets
            #     key: root-password
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  clusterIP: 10.96.0.13
  selector:
    app: mysql-app
  ports:
    - protocol: TCP
      port: 3306
      name: pma
    - protocol: TCP
      port: 3307
      name: wpdb

