USE mysql;
GRANT ALL ON *.* TO 'XuserX'@'%' identified by 'toor' WITH GRANT OPTION ;
GRANT ALL ON *.* TO 'XuserX'@'localhost' identified by 'toor' WITH GRANT OPTION ;
SET PASSWORD FOR 'XuserX'@'localhost'=PASSWORD('toor') ;
DROP DATABASE IF EXISTS test ;
CREATE USER admin@`%` IDENTIFIED BY 'adminpass';
FLUSH PRIVILEGES ;
-- create database phpmyadmin;
-- GRANT all privileges on phpmyadmin.* to mysql@localhost;
-- FLUSH privileges;
