apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-container
        image: nginx-image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: nginx
        - containerPort: 443
          name: nginx-tls
        - containerPort: 22
          name: nginx-ssh
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "/validity.sh"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: nginx-app
  ports:
    - protocol: TCP
      port: 80
      name: nginx
    - protocol: TCP
      port: 443
      name: nginx-tls
    - protocol: TCP
      port: 22
      name: nginx-ssh